packages:
  - "."
  - "packages/*"

linkWorkspacePackages: true

allowBuilds:
  native-gles: true

overrides:
  eventemitter3: 5.0.4

supportedArchitectures:
  os:
    - win32
    - linux
  cpu:
    - x64
