[package]
name = "pixi_node_video"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.12.2", features = ["napi9"] }
napi-derive = "3.2.5"

[target.'cfg(windows)'.dependencies]
rsmpeg = { version = "=0.18.0", default-features = false, features = ["ffmpeg8"] }

[build-dependencies]
napi-build = "2.2.3"
