[package]
name = "pixi_node_video"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = []
native-ffmpeg = ["dep:rsmpeg"]

[dependencies]
napi = { version = "3.12.2", features = ["napi9"] }
napi-derive = "3.2.5"
rsmpeg = { version = "0.18.0", optional = true, default-features = false, features = ["ffmpeg8"] }

[build-dependencies]
napi-build = "2.2.3"
