[package]
name = "pixi_node_window"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.12.2", features = ["napi9"] }
napi-derive = "3.2.5"
sdl3-sys = { version = "0.7.1", features = ["build-from-source"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
napi-build = "2.2.3"
